name: Open a release PR
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true
        type: choice
        options: 
          - alpha
          - patch
          - minor
      base_branch:
        description: Branch to target
        required: true
        type: string
        default: 'releases'

jobs:
  make-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Install cargo-release
        uses: taiki-e/install-action@v1
        with:
          tool: cargo-release

      - uses: actions/checkout@v3
      - uses: cargo-bins/release-pr@v2
        with:
          pr-template-file: .github/release-pr-template.ejs
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
          base-branch: ${{ inputs.base_branch }} 
